server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 123.57.205.173
    username: guest
    password: guest
    virtual-host: /
item:
  rabbitmq:
    exchange: GMALL-PMS-EXCHANGE

mybatis-plus:
  mapper-locations: classpath:mapper/pms/*.xml  # 读取映射文件
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增

